# Generated by Django 4.2.3 on 2023-07-27 03:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='contents',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='contents',
            new_name='content',
        ),
        migrations.AddField(
            model_name='answer',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='수정날짜'),
        ),
        migrations.AddField(
            model_name='question',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='수정날짜'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='작성날짜'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='작성날짜'),
            preserve_default=False,
        ),
    ]
